## ROAD SIGN DETECTION USING KNN CLASSIFIER

In [1]:
#packages,libraries and modules imported and used
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans

In [36]:
#Paths of images saved
folder1=r"Enter your dataset folder path here\dataset\STOP SIGN"

In [37]:
#Feature extraction for stop sign images 

for filename in os.listdir(folder1):
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('Enter your dataset folder path here\dataset\SIFT(LAB13)stop_sign.csv', mode='a', header=False)

In [2]:
#Feature vector of stop sign Dataset
data1= pd.read_csv(r"Enter your dataset folder path here\dataset\SIFT(LAB13)stop_sign.csv")
data1=data1.astype(np.uint8)

#shape
print(data1.shape)

(128119, 128)


In [39]:
#performing kmeans on stop sign class
#stop sign
kmeans1 = KMeans(n_clusters=5)
kmeans1.fit(data1)

KMeans(n_clusters=5)

In [40]:
#histograms of stop sign

hist1=np.histogram(kmeans1.labels_,bins=[0,1,2,3,4,5])
print('histogram of stop sign')
print(hist1,"\n")


histogram of stop sign
(array([20992, 31044, 15286, 21897, 38900], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



In [41]:
#performing kmeans prediction of the entire stop sign dataset with the pretrained kmeans model


#initialising i=0; as its the first class
i=1
data=[]

for filename in os.listdir(folder1):
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans1.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('Enter your dataset folder path here\dataset\SIFT(LAB13)_stopsignFinal.csv', mode='a', header=False)

In [3]:
#Displaying the kmeans predicted data
print("STOP SIGN")
dat1= pd.read_csv(r"Enter your dataset folder path here\dataset\SIFT(LAB13)_stopsignFinal.csv")
print(dat1)

STOP SIGN
     0  156   192   96  204  204.1  1
0    1  166   207   96   88    280  1
1    2  135   287   82  333    347  1
2    3   42    75   45  206     90  1
3    4  372  1325  282  517   1604  1
4    5   39    65   17   55     82  1
..  ..  ...   ...  ...  ...    ... ..
78  79  397   613  206  333    796  1
79  80  102   114  112  196    196  1
80  81  396   395  344  251    620  1
81  82  257   239  209  364    448  1
82  83  364   515  190  471    572  1

[83 rows x 7 columns]


In [43]:
folder2=r"Enter your dataset folder path here\dataset\LEFT TURN"

In [44]:
#Feature extraction for left turn images 

for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('Enter your dataset folder path here\dataset\SIFT(LAB13)left_turn.csv', mode='a', header=False)

In [4]:
#Feature vector of left turn Dataset
data2= pd.read_csv(r"Enter your dataset folder path here\dataset\SIFT(LAB13)left_turn.csv")
data2=data2.astype(np.uint8)
#shape
print(data2.shape)

(144076, 128)


In [46]:
#performing kmeans on left turn class
#left turn
kmeans2 = KMeans(n_clusters=5)
kmeans2.fit(data2)

KMeans(n_clusters=5)

In [47]:
hist2=np.histogram(kmeans2.labels_,bins=[0,1,2,3,4,5])
print('histogram of left turn')
print(hist2,"\n")


histogram of left turn
(array([43612, 24053, 46999, 13213, 16199], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



In [48]:
#performing kmeans prediction of the entire left turn dataset with the pretrained kmeans model
#initialising i=0; as its the first class
i=2
data=[]

for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    a=kmeans2.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('Enter your dataset folder path here\dataset\SIFT(LAB13)_leftturnFinal.csv', mode='a', header=False)

In [5]:
#Displaying the kmeans predicted data
print("LEFT TURN")
dat2= pd.read_csv(r"Enter your dataset folder path here\dataset\SIFT(LAB13)_leftturnFinal.csv")
print(dat2)


LEFT TURN
       0   65  153   99   41   27  2
0      1   27   14   20   38   61  2
1      2  160  214  168   78   88  2
2      3  396  189  604  206  129  2
3      4   27   14   12   35    2  2
4      5  490  210  421  205  159  2
..   ...  ...  ...  ...  ...  ... ..
98    99  323  278  485   72  159  2
99   100   89  171  139   98   52  2
100  101   20   99   57    0   15  2
101  102  707  124  731  101   54  2
102  103  181  350  181  321  648  2

[103 rows x 7 columns]


In [50]:
folder3=r"Enter your dataset folder path here\dataset\MEN AT WORK"

In [51]:
#Feature extraction for men at work images 

for filename in os.listdir(folder3):
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('Enter your dataset folder path here\dataset\SIFT(LAB13)menatwork.csv', mode='a', header=False)

In [6]:
#Feature vector of men at work Dataset
data3= pd.read_csv(r"Enter your dataset folder path here\dataset\SIFT(LAB13)menatwork.csv")
data3=data3.astype(np.uint8)

#shape
print(data3.shape)

(171237, 128)


In [53]:
#performing kmeans on men at work class
#men at work
kmeans3 = KMeans(n_clusters=5)
kmeans3.fit(data3)

KMeans(n_clusters=5)

In [54]:
hist3=np.histogram(kmeans3.labels_,bins=[0,1,2,3,4,5])
print('histogram of men at work')
print(hist3,"\n")

histogram of men at work
(array([18596, 25438, 16661, 55126, 55416], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



In [55]:
#performing kmeans prediction of the entire men at work dataset with the pretrained kmeans model


#initialising i=0; as its the first class
i=3
data=[]

for filename in os.listdir(folder3):
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    a=kmeans3.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('Enter your dataset folder path here\dataset\SIFT(LAB13)_menatworkFinal.csv', mode='a', header=False)

In [7]:
#Displaying the kmeans predicted data
print("MEN AT WORK")
dat3= pd.read_csv(r"Enter your dataset folder path here\dataset\SIFT(LAB13)_menatworkFinal.csv")
print(dat3)


MEN AT WORK
     0   30   76   23   122  76.1  3
0    1  236  318  182   714   729  3
1    2  109  390   87   158   135  3
2    3   28  147   27   110   124  3
3    4  185  122   82   481   514  3
4    5  176  112  101   421   369  3
..  ..  ...  ...  ...   ...   ... ..
94  95  154  294  246   892  1081  3
95  96  203  227  124   745   731  3
96  97  295  314  267  1483  1519  3
97  98  396  433  291   589   651  3
98  99  223  174  194   548   600  3

[99 rows x 7 columns]


In [57]:
folder4=r"Enter your dataset folder path here\dataset\GO RIGHT"

In [58]:
#Feature extraction for go right images 

for filename in os.listdir(folder4):
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('Enter your dataset folder path here\dataset\SIFT(LAB13)goright.csv', mode='a', header=False)

In [8]:
#Feature vector of go right Dataset
data4= pd.read_csv(r"Enter your dataset folder path here\dataset\SIFT(LAB13)goright.csv")
data4=data4.astype(np.uint8)

#shape
print(data4.shape)

(97605, 128)


In [60]:
#performing kmeans on each class
#go right
kmeans4 = KMeans(n_clusters=5)
kmeans4.fit(data4)

KMeans(n_clusters=5)

In [61]:
hist4=np.histogram(kmeans4.labels_,bins=[0,1,2,3,4,5])
print('histogram of go right')
print(hist4,"\n")

histogram of go right
(array([29906, 10185, 16620, 31279,  9615], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



In [62]:
#performing kmeans prediction of the entire go right dataset with the pretrained kmeans model


#initialising i=0; as its the first class
i=4
data=[]

for filename in os.listdir(folder4):
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    array_double = np.array(out, dtype=np.double)
    a=kmeans4.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('Enter your dataset folder path here\dataset\SIFT(LAB13)_gorightFinal.csv', mode='a', header=False)

In [9]:
#Displaying the kmeans predicted data
print("GO RIGHT")
dat4= pd.read_csv(r"Enter your dataset folder path here\dataset\SIFT(LAB13)_gorightFinal.csv")
print(dat4)

GO RIGHT
     0   192   27  130   128   83  4
0    1   163   81   62   143  147  4
1    2   349  298  153   409  211  4
2    3  1710  481  396  1502  580  4
3    4   631  167  406   550  204  4
4    5   747  153  504   949  149  4
..  ..   ...  ...  ...   ...  ... ..
66  67   800  315  300   898  161  4
67  68    29    5   47    22   19  4
68  69   479  197  172   540  140  4
69  70   707  260  416   677  273  4
70  71   216  114  370   266  118  4

[71 rows x 7 columns]


In [14]:
#appending All classes into 1 csv file

A=dat1.append(dat2)
A=A.append(dat3)
A=A.append(dat4)

csv_data=A.to_csv('SIFT(LAB14)_Final.csv', mode='a', header=False)

In [2]:
data= pd.read_csv(r"D:\PYTHON\COMPUTER VISION\COURSE PROJECT\dataset\SIFT(LAB14)_Final.csv")
data.columns=['No_of_feature','1','2','3','4','5','Class']
print(data)

     No_of_feature    1     2    3    4     5  Class
0                2  135   287   82  333   347      1
1                3   42    75   45  206    90      1
2                4  372  1325  282  517  1604      1
3                5   39    65   17   55    82      1
4                6  150   143  139  220   144      1
..             ...  ...   ...  ...  ...   ...    ...
350             67  800   315  300  898   161      4
351             68   29     5   47   22    19      4
352             69  479   197  172  540   140      4
353             70  707   260  416  677   273      4
354             71  216   114  370  266   118      4

[355 rows x 7 columns]


In [3]:
#assigning x the columns from 1 to 5 for training
x = data.iloc[:, 1:6]
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data['Class']
print("Y values")
print(y)

X values
       1     2    3    4     5
0    135   287   82  333   347
1     42    75   45  206    90
2    372  1325  282  517  1604
3     39    65   17   55    82
4    150   143  139  220   144
..   ...   ...  ...  ...   ...
350  800   315  300  898   161
351   29     5   47   22    19
352  479   197  172  540   140
353  707   260  416  677   273
354  216   114  370  266   118

[355 rows x 5 columns]
Y values
0      1
1      1
2      1
3      1
4      1
      ..
350    4
351    4
352    4
353    4
354    4
Name: Class, Length: 355, dtype: int64


In [4]:
#standard scaling
from pandas import DataFrame
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x=DataFrame(x)
x

0         1         2         3         4
0   -0.590267  0.166369 -0.695175 -0.022870  0.030348
1   -0.892064 -0.893110 -0.833501 -0.402224 -0.713153
2    0.178830  5.353818  0.052529  0.526746  3.666846
3   -0.901800 -0.943085 -0.938179 -0.853268 -0.736296
4   -0.541590 -0.553277 -0.482080 -0.360406 -0.556931
..        ...       ...       ...       ...       ...
350  1.567747  0.306300  0.119822  1.664810 -0.507750
351 -0.934251 -1.242938 -0.826024 -0.951841 -0.918555
352  0.526059 -0.283410 -0.358708  0.595448 -0.568503
353  1.265949  0.031435  0.553491  1.004674 -0.183734
354 -0.327411 -0.698206  0.381519 -0.223002 -0.632149

[355 rows x 5 columns]

In [5]:
#Dataset split into train and test with 80% Training and 20% Testing
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

In [16]:
# import sklearn.metrics as metrics
# from sklearn.metrics import accuracy_score

# from sklearn import svm

# #Create a svm Classifier
# model1 = svm.SVC(kernel='linear')


# #Train the model using the training sets
# model1.fit(x_train, y_train)

# #Predict the response for test dataset
# y_pred1 = model1.predict(x_test)
# #Results
# print("SVM Results")
# print(classification_report(y_test, y_pred1))
# print("SVM: ",accuracy_score(y_test, y_pred1))

import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
#Create a KNN Classifier
model = KNeighborsClassifier(n_neighbors = 8)

#Train the model using the training sets
model.fit(x_train,y_train)

#Predict the response for test dataset
pred=model.predict(x_test) 
#Results
print("KNN Results")
print(classification_report(y_test, pred))
print("KNN: ",accuracy_score(y_test, pred))

KNN Results
              precision    recall  f1-score   support

           1       0.74      0.70      0.72        20
           2       0.91      1.00      0.95        20
           3       0.75      0.78      0.77        23
           4       1.00      0.75      0.86         8

    accuracy                           0.82        71
   macro avg       0.85      0.81      0.82        71
weighted avg       0.82      0.82      0.82        71

KNN:  0.8169014084507042


In [21]:
#Recognition &Validation
#Assigning path with any any class image
path=r"D:\PYTHON\COMPUTER VISION\COURSE PROJECT\dataset\STOP SIGN\1.jpg"
data=[]

#Repeated the process of image pre-processing and feature extraction
a=cv2.imread(path)
resize=(512,512)

#resize image
img=cv2.resize(a,resize)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#initialise sift descriptor
sift = cv2.xfeatures2d.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(gray, None)

#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)

#initialise Kmeans and create 5 clusters
kmeans = KMeans(n_clusters=5)

#train the model for the features i.e. for all elements in the Dataframe
kmeans.fit(out.values)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the hostogram for all those vlaues
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print(Output)

     0    1    2    3    4
0  109  159  153  191  240


In [22]:
# # #assigning the columns 1 to 128 of new image as training variables
x = Output.iloc[:, 0:5]
from sklearn.preprocessing import StandardScaler
x=sc.transform(x)

#prediction
y_pred1 = model.predict(x)

#prints the prediction of the class
print(y_pred1)

[1]


In [30]:
if ((y_pred1)==1):
    print("stop sign")
elif ((y_pred1)==2):
    print("left turn")
elif ((y_pred1)==3):
    print("men at work")
else:
    print("go right")

stop sign
